apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fast-api-test
  namespace: knative-serving
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "300"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "2"
        autoscaling.knative.dev/scale-down-delay: "10m"
    spec:
      containers:
        - image: samgarvis/fast-api-test:latest
          ports:
            - containerPort: 80
              
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
              
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
